# Generated by Django 4.1.4 on 2022-12-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cast',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='cast',
            field=models.ManyToManyField(to='main_app.cast'),
        ),
    ]
